language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

notifications:
  slack:
    rooms:
      - secure: "Ku+j0Tz9tdumY7AXgKjH8IdcZr/gogYD3EZI3iHEnf9lq/mlqwbD3qYFUL73I8bJtQor9yrkfEclQIlD2k9HCW6lTBpxP0IbK8NFwDPP+EXPtPi6viYSueBZ586jJN/qyfxPS9wcfRY0kiUcbZGF7tooc+diiK3i/MaKAL8+qLjV0tzBqpaV/8S/S7FYSuFYYwu/9DuWulv2hPv131IzRoPYhmBx+wCoeaI7XpbpjqRbXoypvTox3mzug0O8pQNaIJWBqmd6H0bCq+MaK+eHa0PehHfdvA25iP+Au7WyeeG+5VMQeesg7vZXeznhlGZh1WsZ/LfifExYacCyqG01SynBuvvr7m8yL9G/ewNa3gThKYcYAalLRtXn9Ptx8gRnzwdy1ib0D1yVCZuS4cKkqJIKibZ1COzu/FMtA96LSWv5D/lwd9jmfo+t8nSoZAhLfpTjzmTNn3Ahy0JfXJGRTESpjfhCyu7438yDHFB1UYFVDJmOeyBxLAUWYbKwR9o/VEnl1Cb/0q868BdxYklyZc6SAFjRgI/5fwpAUC6TgIv8pJlFe3oo4zgkkg2yx2B7l2m56mxMggxesRiaezIB62djOyH183Gh6ajJgUiAiFRRZCDS42X7uMklvzhU+2iFrnWlhzPKI7fRHL7SewoFun262MmOi6YUCm4xjEe4jbg="
    on_success: always

env:
  matrix:
    - LARAVEL=5.8.*
    - LARAVEL=dev-master

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: LARAVEL=dev-master
  allow_failures:
    - env: LARAVEL=dev-master

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

install:
  - travis_retry composer require "illuminate/contracts=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit --verbose
