language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: setup=lowest
    - php: 7.2
    - php: 7.2
      env: setup=lowest
    - php: 7.3
    - php: 7.3
      env: setup=lowest
  allow_failures:
    - php: 7.3

sudo: false

before_install:
- phpenv config-rm xdebug.ini

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: vendor/bin/phpunit --verbose